# (PART) Syllabus {-}

# Course Introduction

> Figures often beguile me, particularly when I have the arranging of them myself; in which case the remark attributed to Disraeli would often apply with justice and force: ‘There are three kinds of lies: lies, damned lies, and statistics’.

**Mark Twain (1906)**

</br>

This course provides an introduction to applied statistical analysis for both undergraduate and graduate students with an emphasis placed on statistical techniques that are most common in the sociological literature. The statistical techniques introduced include measures of central tendency and dispersion as well as measures of bi-variate association. Multivariate statistical analyses are also introduced along with essential skills for cleaning data, creating plots, and reporting results. While the examples may be specific to the social sciences, the theories and skills that are covered are broadly applicable across academic disciplines.

## Course Objectives

This course has four intertwined objectives. After completing the
course, students will be able to:

1.  *Fundamentals of inferential statistics*: Describe the use of
    various statistical tests, their requirements and assumptions, and
    their interpretation; execute these tests both by hand and
    programmatically using `R`.

2.  *Fundamentals of data analysis*: Perform basic data cleaning and
    analysis tasks programmatically using `R` in ways that support high
    quality documentation and replication.

3.  *Fundamentals of data visualization*: Create and present publication
    quality plots programmatically using `R` and `ggplot2`.

4.  *Quantitative research synthesis*: Plan, implement (using `R`), and
    present (using LaTeX and the presentation software of your
    choice) a research project that uses linear regression to answer a
    research question.
    
## Core Resources

There are three core documents and resources for this course. This **Syllabus** sets out core expectations and policies for the course - i.e. what is *required* for this course.. It includes a **Reading List** that contains topics, readings (both required and optional), and assignment due dates for each week. Once the semester starts, these documents will only be updated if a schedule change is necessary.

In addition to these documents, regular updates will be provided on the [**course website**](https://slu-soc5050.github.io). Each week will have a corresponding page on the site that includes links to handouts, YouTube videos, sample code, and additional descriptions of concepts covered in class. Please check the website regularly for updates and new content.

All of our course content will be hosted through GitHub, where we have a [**course organization**](https://github.com/slu-soc5050). The course organization will contain *repositories* (a special type of folder) for each lecture as well as several repositories dedicated to specific aspects of the course. These repositories should be cloned as they are released and synced as they are updated. 

## Readings

There are three books required for this course with an optional fourth book. Each book has been selected to correspond with one or more of the course objectives. The books are:

1. Diez, David M., Christopher D Barr, and Mine Cetinkaya-Rundel-Runde. 2015. *OpenIntro Statistics*. 3rd edition. OpenIntro.
    * This book is **not** available from the Bookstore. You can [download a free copy](https://www.openintro.org/stat/textbook.php) or purchase a physical copy from Amazon ([black & white](https://www.amazon.com/dp/1943450048/) or [color](https://www.amazon.com/dp/1943450056/)).
2. Wheelan, Charles. 2014. *Naked Statistics: Stripping the Dread from the Data*. New York, NY: W. W. Norton & Company.
    * This book can be purchased in the bookstore or online. Ebook versions are available.
3. Wickham, Hadley and Garrett Grolemund. 2017. *R for Data Science*. O’Reily Media: Sebastopol, CA.
    * This book book can be purchased in the bookstore, online, or accessed for free [as a webbook](http://r4ds.had.co.nz).

I do not require students to buy physical copies of texts. You are free to select a means for accessing these texts that meets your budget and learning style. If ebook editions (e.g. Kindle, iBooks, `pdf`, etc.) of texts are available, they are acceptable for this course. All texts should be obtained in the edition noted above.

All readings are listed on the **Reading List** and should be completed before the course meeting on the week in which they are assigned. Full text versions of most readings not found in the books assigned for the course can be obtained using the library’s [Electronic Reserves](http://eres.slu.edu/eres/coursepass.aspx?cid=4487) system. The password for the Electric Reserves will be posted on Slack at the beginning of the semester.
