# Course Policies

My priority is that class periods are productive learning experiences for all students. In order to foster this type of productive environment, I ask students to follow a few general policies and expectations:

1.  Work each week to contribute to a positive, supportive, welcoming, and compassionate class environment.
2.  Arrive to class on time and stay for the entire class period.
3.  Silence *all* electronic devices before entering the classroom.
4.  Do not engage in side conversations. This is disrespectful to the speaker (whether me or a classmate), and can affect the ability of others in the class to learn.
5.  Be respectful of your fellow classmates. Do not interrupt when someone is speaking, monopolize the conversation, or belittle the ideas or opinions of others.
6.  Complete the assigned readings for each class in advance, and come prepared with discussion points and questions.
    
The following sections contain additional details about specific course policies related to attendance, participation, electronic device use, student support, academic honesty, and Title IX.

## Compassionate Coursework

> Being around people who are different from us makes us more creative, more diligent and harder-working

**[Katherine Phillips, 2014](https://www.scientificamerican.com/article/how-diversity-makes-us-smarter/)**

</br>
The goal of this course is not just to impart knowledge related to statistics and data science, but to purposefully create an environment where all students feel welcome and supported even as they feel challenged intellectually. This is especially important in a STEM course, where stress levels among students can be generally high. For those of you who have not had significant mathematical coursework since High School, or have not written computer code before, that could be enough to treat statistics coursework with apprehension. Feeling at least a little anxious about a course like this is understandable and to be expected. 

In response to this stress, students sometimes develop "impostor syndrome", a feeling that academic gains are not the result of their own abilities and a fear that they will soon be "found out" ([Cooper et al. 2018](https://www.physiology.org/doi/10.1152/advan.00085.2017), [Lindemann et al. 2016](http://genderandset.open.ac.uk/index.php/genderandset/article/view/435)). This is reported with particular frequency by students from social groups traditionally underrepresented in STEM courses ([Malone and Barabino 2008](https://onlinelibrary.wiley.com/doi/pdf/10.1002/sce.20307), [Ong 2005](https://doi.org/10.1525/sp.2005.52.4.593), [Ong et al. 2011](https://doi.org/10.17763/haer.81.2.t022245n7x4752v2)). Taking these concerns seriously is imperative not just for reasons of academic retention and its future implications ([Akinnawonu 2017](https://open.nytimes.com/why-having-a-diverse-team-will-make-your-products-better-c73e7518f677), [Diaz-Garcia et al. 2011](https://www.tandfonline.com/doi/abs/10.5172/impp.2013.15.2.149), [Hill et al. 2010](https://www.aauw.org/aauw_check/pdf_download/show_pdf.php?file=why-so-few-research), [Nathan and Lee 2015](https://www.tandfonline.com/doi/abs/10.1111/ecge.12016)), but also because we are called to do so by the [University's mission](https://www.slu.edu/about/catholic-jesuit-identity/mission.php) both in our classrooms and in the wider world. 

If you are feeling stressed about the coursework, feel like it is taking what seems like an excessive amount of time, or want to talk about strategies for problem solving, please reach out during class, office hours, or via Slack. This will be my tenth semester teaching research methods, and I have plenty of strategies for success in these courses that I am happy to share!

### Code of Conduct

While I take a leading role in fostering a welcoming and supportive environment, I need each student's help in making that environment a reality. To that end, you should familiarize themselves with [Contributor Covenant's](https://www.contributor-covenant.org) [Code of Conduct](https://www.contributor-covenant.org/version/1/4/code-of-conduct), which is increasingly included in open source projects and is included with each lecture repository on [GitHub](https://github.com/slu-soc5050). The Code of Conduct lays out expectations for how all students should to conduct themselves. I want to emphasize one piece here in the syllabus, which includes concrete examples of things each student *can* and *should* do to help create a compassionate class atmosphere:

> Examples of behavior that contributes to creating a positive environment include: using welcoming and inclusive language, being respectful of differing viewpoints and experiences, gracefully accepting constructive criticism, focusing on what is best for the [class], [and] showing empathy towards other community members

The degree to which students are positively engaged with our class along these lines will be reflected in participation grades given at the mid and end points of the semester. If you feel that a colleague's conduct is not in line with creating compassionate coursework experience, you are encouraged to speak to me. I will treat all discussions with discretion and will work with you to make a plan for addressing any concerns you might have.

### Harrassment and Title IX

While I have every expectation that each member of the Saint Louis University community is capable and able to treat community members with dignity and respect, I fully recognize that there may be instances where students fall short of that expectation. Students should generally be aware that: 

> Saint Louis University prohibits harassment because of sex, race, color, religion, national origin, ancestry, disability, age, sexual orientation, marital status, military status, veteran status, gender expression/identity, genetic information, pregnancy, or any other characteristics protected by law.

All students should also familiarize themselves with [Saint Louis University’s polices](http://www.slu.edu/general-counsel-home/office-of-institutional-equity-and-diversity) on bias, discrimination, harassment, and sexual misconduct. In particular, they should be aware of policies on [harassment](https://www.slu.edu/general-counsel/institutional-equity-diversity/pdfs/harassment-policy.pdf) and [sexual misconduct](https://www.slu.edu/about/safety/sexual-assault-resources.php):

> Saint Louis University and its faculty are committed to supporting our students and seeking an environment that is free of bias, discrimination, and harassment. If you have encountered any form of sexual misconduct (e.g. sexual assault, sexual harassment, stalking, domestic or dating violence), we encourage you to report this to the University. If you speak with a faculty member about an incident of misconduct, that faculty member must notify SLU’s Title IX Coordinator, Anna R. Kratky (DuBourg Hall, Room 36; <anna.kratky@slu.edu>); 314-977-3886) and share the basic facts of your experience with her. The Title IX coordinator will then be available to assist you in understanding all of your options and in connecting you with all possible resources on and off campus. 

> If you wish to speak with a confidential source, you may contact the counselors at the University Counseling Center at 314-977-TALK.

Instances of abusive, harassing, or otherwise unacceptable behavior should be reported either directly to the instructor or to the University Administration. Consistent with the above policies, I will forward all reports of inappropriate conduct to the Title IX Coordinator’s office or to the Office of Diversity and Affirmative Action. Please be aware that University policies may require me to forward information about the identity of any students connected to the disclosure.

Please also be aware that communications over various online services, including (but not limited to) Slack, GitHub, and Google Apps, are covered by this policy.

## Attendance and Participation

Attendance and participation are important components of this course since we only meet once a week. Students are expected to attend all class sessions; missing even one class can create a significant roadblock for many students. If you cannot attend class or arrive on time because of a personal illness, a family issue, jury duty, an athletic match, or a religious observance, you must contact me **beforehand** to let me know. I may ask for more information, such as a note from a physician, a travel letter from Athletics, or other documentation for absences. 

A penalty will not be applied to your first unexcused absence or late arrival. Any absences or late arrivals beyond the first will result in no credit (for an absences) or only partial credit (for a late arrival) being earned for that day's participation grade.

Making up missed classes are your responsibility. I do post slide decks on the course website, but my slides are intended only to serve as references. This semester, I am also **experimenting** with Tegrity recordings for this course. Recordings will typically be posted within 24-hours of class and will be linked to through the course website.

The academic literature (see [this recent article](https://link.springer.com/article/10.1007/s10734-018-0275-9) for a nice overview) suggests that the impact of lecture capture tools like Tegrity is mixed at best. Students tend to rate their experience with lecture capture far more positively than faculty do. Students who continue to attend class regularly and use lecture recordings as part of an *active* approach to studying and filling in specific areas of their notes may benefit from recordings. Students who use recordings as a replacement for attending class do not benefit from the recordings.

Please also note that lectures and discussions cannot be recorded by any means (e.g. audio or video recordings, or photographs) without my permission.

## Communication

Slack and email are my preferred methods of communication.

I am on Slack during workday hours, though I may be "away" during meetings and while I teach my other class. I also may have limited availability on Tuesdays, a day that I am not typically on-campus. I will also monitor Slack during weekday evening hours and will respond to messages if I am able. Likewise, I dedicate time to email responses each workday, meaning that my response time is typically within 24 hours during the workweek. Please use your SLU email account when emailing me.

For both email and Slack, if you have not received a response from me after 48 hours (or by end of business on Monday if you messaged me over the weekend), please follow-up to ensure that your message did not get lost in the shuffle.

All messages regarding course updates, assignments, and changes to the class schedule, including cancellations, will be posted on the `_news` channel in Slack. Changes to the class schedule, including cancellations, will also sent to your SLU email account. It is imperative that you check both Slack and your SLU email account regularly.

Please also ensure that all concerns or questions about your standing in the course are directed to me immediately. Inquires from parents, SLU staff members, and others will not be honored.

## Electronic Devices

During class periods, students are asked to refrain from using electronic devices (including cell phones) for activities not directly related to the course. For this class, I expect students to limit their use of electronic devices to accessing course software, readings, and notes.

There is evidence that using electronic devices during lectures results in decreased retention of course content ([Hembrooke and Gay 2003](https://link.springer.com/article/10.1007/BF02940852)) and lower overall course performance ([Fried 2008](https://www.sciencedirect.com/science/article/pii/S0360131506001436)). Students who are not using a laptop but are in direct view of another student’s laptop also have decreased performance in courses ([Sana et al. 2013](https://www.sciencedirect.com/science/article/pii/S0360131512002254)). Conversely, students who take notes the “old fashioned way” have better performance on tests compared to students who take notes on laptops ([Mueller and Oppenheimer 2014](http://journals.sagepub.com/doi/abs/10.1177/0956797614524581)).

I therefore ask students to be conscious of how they are using their devices, the ways such use impacts their own learning, and the effect that it may have on others around them. I reserve the right to alter this policy if electronic device use becomes problematic during the semester.

## Student Support

### Basic Needs

If you have difficulty affording groceries or accessing sufficient food to eat every day, or lack a safe and stable place to live, you are urged to contact the [Dean of Students](https://www.slu.edu/student-development/dean-of-students/index.php) for support. Likewise if you have concerns about your mental or physical health needs, or lack access to health care services you require, you should contact either the [Dean of Students](https://www.slu.edu/student-development/dean-of-students/index.php), [Student Health Services](https://www.slu.edu/life-at-slu/student-health/index.php), or the [University Counseling Center](https://www.slu.edu/life-at-slu/university-counseling/index.php).^[This language is adopted from text written by [Dr. Sarah Goldrick-Rab](https://medium.com/@saragoldrickrab/basic-needs-security-and-the-syllabus-d24cc7afe8c9).]

If you feel comfortable doing so, please discuss any concerns you might have with me. Doing so is particularly important if believe your performance in this course might be affected. I will do my best to work with you to come up with a plan for successfully completing the course and, if need be, work with you to identify on-campus resources. I will treat all discussions with discretion, though please be aware that certain situations, including disclosures of [sexual misconduct](/compassionate-coursework.html) or self harm, must be reported by faculty to the appropriate University office.

### Academic Accommodations 

If you meet the eligibility requirements for academic accommodations through the [Office of Disability Services](https://www.slu.edu/life-at-slu/student-success-center/disability-services/index.php) (located within the Student Success Center) *and you wish to use them for this class*, you should arrange to discuss your needs with me after the first class. All discussions of this nature are treated confidentially, and I will make every effort to work with you to come up with a plan for successfully completing the course requirements. Please note that I will not provide accommodations to students who are not working with Disability Services, and that I cannot retroactively alter assignments or grades if they have already been completed.

### Writing Services

I also encourage you to take advantage of the [University Writing Services (UWS) program](https://www.slu.edu/life-at-slu/student-success-center/academic-support/university-writing-services/index.php). Getting feedback benefits writers at all skill levels and the quality of your writing will be reflected in assignment grades. The UWS has trained writing consultants who can help you improve the quality of your written work. UWS’s consultants are available to address everything from brainstorming and developing ideas to crafting strong sentences and documenting sources.

### Student-athletes

If you are a student-athlete who is in-season, you should discuss your game schedule with me after the first class and share your travel letter with me as soon as you have a copy. You are reminded that games and tournaments are not excuses for failing to complete assignments, and that NCAA rules prohibit student-athletes from missing classes for practice. Low grades that jeopardize eligibility must be addressed immediately by you, not by a coach or academic coordinator.

## Academic Honesty

All students should familiarize themselves with [Saint Louis University’s policies](http://www.slu.edu/Documents/provost/academic_affairs/Academic%20Integrity%20Policy%20FINAL%20%206-26-15.pd) concerning cheating, plagiarism, and other academically dishonest practices:

> Academic integrity is honest, truthful and responsible conduct in all academic endeavors. The mission of Saint Louis University is “the pursuit of truth for the greater glory of God and for the service of humanity.” Accordingly, all acts of falsehood demean and compromise the corporate endeavors of teaching, research, health care, and community service via which SLU embodies its mission. The University strives to prepare students for lives of personal and professional integrity, and therefore regards all breaches of academic integrity as matters of serious concern.

Any work that is taken from another student, copied from printed material, or copied the internet without proper citation is expressly prohibited. Note that this includes all computer code, narrative text, and documentation written for class assignments - each student is expected to author and de-bug their notebooks and accompanying files.

All relevant assignments should include in-text citations and references formatted using the [American Sociological Association (ASA)](https://owl.english.purdue.edu/owl/resource/583/1/) style guidelines. Any student who is found to have been academically dishonest in their work risks failing both the assignment and this course.
