# (PART) Reading List {-}

# Course Schedule

The following is a high-level schedule that details the general topic covered by each lecture.

```{r, echo=FALSE}
schedule <- data.frame(
  Lecture = c("", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", ""),
  Date = c("prior to August 27^th^", "August 27^th^", "September 3^rd^", "September 10^th^", "September 17^th^", "September 24^th^", "October 1^st^", "October 8^th^", "October 15^th^", "October 22^nd^", "October 29^th^", "November 5^th^", "November 12^th^", "November 19^th^", "November 26^th^", "December 3^rd^", "December 10^th^", "December 17^th^"),
  Topic = c("Course Preview", "Course Introduction", "Working with Data", "Describing Distributions", "Probability", "The Distribution of Random Variables", "Foundations for Inference", "Difference of Means (Part 1)", "Difference of Means (Part 2)", "Working with Factors", "Correlations (Part 1)", "Correlations (Part 2)", "OLS Regression (Part 1)", "OLS Regression (Part 2)", "OLS Regression (Part 3)", "Analysis of Variance", "Chi-Squared", "Final Presentations"),
  stringsAsFactors = FALSE
)

knitr::kable(
  schedule, booktabs = TRUE,
  caption = "SOC 4015 and 5050 Course Overview"
)
```

## Planned Online Lectures

This semester, we have two classes that fall on official university holidays: Labor Day (Lecture-02, **September 3^rd^**) and Fall Break (Lecture-09, **October 22^nd^**). These weeks will have materials assigned for them, which will include lectures posted on YouTube. These lectures will be shorter than typical in-class lectures. Students should view these lectures during that week and complete the associated readings and lab exercises. Videos will be embedded in the lecture pages on the [**course website**](https://slu-soc5050.github.io/).

## Class Progression

Each lecture will be broken down roughly the same way. Students are expected to arrive having already completed the previous week's work as well as the assigned readings and lecture prep. Class will begin with any relevant "front matter" including follow-up from the previous weeks and relevant announcements. When assigned, we will then segue into a discussion of the Wheelan text before spending the majority of class focused on the day’s main topic, which will typically be related to one or more of the first three learning outcomes. Around 6:00pm, we will take a short break. Most classes will end with time dedicated to working through the lab exercise. After class, students are expected to finish the lab and, if necessary, the assigned problem set as well.

## Scheduling Notes

The lecture schedule may change as it depends on the progress of the class. However, you must keep up with the reading assignments. In the event of a cancellation due to weather or another disruption, I may alter the lecture schedule.

Since this course only meets once per week, cancellations are particularly disruptive. I will make every effort to schedule make-up classes at a time that works for at least a portion of the class. These class sessions will be recorded and made immediately available using YouTube for students who are unable to attend the make-up class. All students will be responsible for either attending the make-up class or watching the lecture as well as completing all readings, lab assignments, and problem sets for make-up classes.
